# Site settings
title: bmcculley
description: Just another blog on the internet.
url: https://bmcculley.github.io
github_username: bmcculley
cloudfront_url: https://bmcculley.github.io

# Build settings
markdown: kramdown
permalink: ordinal
