# Site settings
title: bmcculley
description: bmcculley is a freelance Python developer with 10+ years of experience with project development and management that results in 100% customer satisfaction.
url: https://bmcculley.ejank.com
github_username: bmcculley
cloudfront_url: https://bmcculley.ejank.com

# Build settings
markdown: kramdown
permalink: ordinal
