# Site settings
title: bmcculley
description: A Freelance Python Developer. Looking for a programmer for hire? Get a professional with 10+ years Python experience and get your project completed today.
url: https://bmcculley.ejank.com
github_username: bmcculley
cloudfront_url: https://d6v9x51arm3r7.cloudfront.net

# Build settings
markdown: kramdown
permalink: ordinal
